href_tuto: https://www.railstutorial.org/
href_rails: http://rubyonrails.org/
href_auth: http://www.michaelhartl.com/
href_help: https://www.railstutorial.org/help
href_book: https://www.railstutorial.org/book
email: from@example.com
